# Generated by Django 4.0.8 on 2022-12-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starsofrating',
            options={'ordering': ['value'], 'verbose_name': 'Звезды рейтинга ', 'verbose_name_plural': 'Общий рейтинг'},
        ),
    ]
