# Generated by Django 4.0.8 on 2023-02-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_category_description_en_category_description_ru_and_more'),
    ]

    operations = [
    ]
