# Generated by Django 4.0.8 on 2023-02-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_release_alter_movie_year'),
    ]

    operations = [
    ]
