# Generated by Django 4.0.8 on 2023-02-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_year_movie_release'),
    ]

    operations = [
    ]
